---
title: "Emission Data - Exploratory Data Analysis"
author: "Macarena L. Fernandez Carro"
date: "2024-02-12"
output: html_document
---

```{R}
library(ggplot2)
library(lattice)
library(dplyr)
library(RColorBrewer)


```
# EXPLORATORY DATA ANALYSIS WITH R

The overall goal of this assignment is to explore the National Emissions Inventory database and see what it say about fine particulate matter pollution in the United states over the 10-year period 1999–2008. You may use any R package you want to support your analysis.

## Questions
You must address the following questions and tasks in your exploratory analysis. For each question/task you will need to make a single plot. Unless specified, you can use any plotting system in R to make your plot.

1. Have total emissions from PM2.5 decreased in the United States from 1999 to 2008? Using the base plotting system, make a plot showing the total PM2.5 emission from all sources for each of the years 1999, 2002, 2005, and 2008.

2. Have total emissions from PM2.5 decreased in the Baltimore City, Maryland (fips == "24510") from 1999 to 2008? Use the base plotting system to make a plot answering this question.

3. Of the four types of sources indicated by the  type (point, nonpoint, onroad, nonroad) variable, which of these four sources have seen decreases in emissions from 1999–2008 for Baltimore City? Which have seen increases in emissions from 1999–2008? Use the ggplot2 plotting system to make a plot answer this question.

4. Across the United States, how have emissions from coal combustion-related sources changed from 1999–2008?

5. How have emissions from motor vehicle sources changed from 1999–2008 in Baltimore City?

6. Compare emissions from motor vehicle sources in Baltimore City with emissions from motor vehicle sources in Los Angeles County, California (fips == "06037"). Which city has seen greater changes over time in motor vehicle emissions?

```{R}
## READ THE DATA

NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")
```

### Question 1:

Have total emissions from PM2.5 decreased in the United States from 1999 to 2008? --> YES THE EMISSIONS HAVE BEEN DEMINISHED

Using the base plotting system, make a plot showing the total PM2.5 emission from all sources for each of the years 1999, 2002, 2005, and 2008.

```{R}
while (!is.null(dev.list()))  dev.off()
#Calculate the total emissions by year

totalPM25ByYear <- tapply(NEI$Emissions, NEI$year, sum)

#Plot the results

png("plot1.png")
plot(names(totalPM25ByYear), 
     totalPM25ByYear,
     type = "l",
     xlab = "Year",
     ylab = expression("Total US" ~ PM[2.5] ~ "Emissions (Tons)"),
     main = expression("Total US" ~ PM[2.5] ~ "Emissions by Year"))
dev.off()

```
### Question 2:

2. Have total emissions from PM2.5 decreased in the Baltimore City, Maryland (fips == "24510") from 1999 to 2008? --> YES THEY HAVE DECREASED

Use the base plotting system to make a plot answering this question.

```{R}
# Gather the data for Baltimore

BaltimoreData <- subset(NEI, fips == "24510")

# Plot the results

png("plot2.png")
plot(names(totalPM25ByYear),
     totalPM25ByYear,
     type = "l",
     xlab = "Year",
     ylab = expression ("Total" ~ PM[2.5] ~ "Emissions (Tons)"),
     main = expression ("Total" ~ PM[2.5] ~ "Emissions in Baltimore City by Year"))
dev.off()
```

### Question 3: 

Of the four types of sources indicated by the  type (point, nonpoint, onroad, nonroad) variable: 

Which of these four sources have seen decreases in emissions from 1999–2008 for Baltimore City? 

Which have seen increases in emissions from 1999–2008? 

Use the ggplot2 plotting system to make a plot answer this question.

```{R}
# Perform calculations

TypePMPM25ofBMar <- BaltimoreData %>%
  select (year, type, Emissions) %>%
  group_by(year, type) %>%
  summarise_each(funs(sum))

#Plot 
png("plot3.png")
TypePMPM25ofBMar %>%
ggplot(aes(x = year,
           y = Emissions,
           color = type)) +
  geom_line() +
  scale_color_brewer(palette = "Dark2") +
  ggtitle( label = "Emissions by Source Type and Year",
           subtitle = "Baltimore City") +
  xlab("Year") + 
  ylab(expression("Total" ~ PM[2.5] ~ "Emissions (Tons)"))
dev.off()
```

### Question 4

Across the United States, how have emissions from coal combustion-related sources changed from 1999–2008? --> THEY HAVE REDUCED

```{R}
#Gather coal - combustion only data

CoalCombustionSCC0 <- subset(SCC,
                            EI.Sector %in% c("Fuel Comb - Comm/Instutional - Coal",
                                                  "Fuel Comb - Electric Generation - Coal",
                                                  "Fuel Comb - Industrial Boilers, ICEs - Coal")) 

# Compare to Short.Name matching both Comb and Coal
CoalCombustionSCC1 <- subset(SCC, grepl("Comb", Short.Name) & 
                                  grepl("Coal", Short.Name))

print(paste("Number of subsetted lines via EI.Sector:", nrow(CoalCombustionSCC0)))
print(paste("Number of subsetted lines via Short.Name:", nrow(CoalCombustionSCC1)))

# set the differences
diff0 <- setdiff(CoalCombustionSCC0$SCC, CoalCombustionSCC1$SCC)
diff1 <- setdiff(CoalCombustionSCC1$SCC, CoalCombustionSCC0$SCC)

print(paste("Number of setdiff (data via EI.Sector & Short.Name):", length(diff0)))
print(paste("Number of setdiff (data via Short.Name & EI.Sector):", length(diff1)))

# Create the union of SCCs via EI.Sector & Short.Name
CoalCombustionSCCCodes <- union(CoalCombustionSCC0$SCC,
                                CoalCombustionSCC1$SCC)
print(paste("Number of SCCs:", length(CoalCombustionSCCCodes)))

# Fetch needed NEI data via SCCs
CoalCombustion <- subset(NEI, SCC %in% CoalCombustionSCCCodes)

# Calculate the sum of emission by type and year
coalCombustionPM25ByYear <- CoalCombustion %>% select(year, 
                                                      type, 
                                                      Emissions) %>%
                                               group_by(year, 
                                                        type) %>%
                                               summarise_each(funs(sum))

#Plot the results

png("plot4.png")
coalCombustionPM25ByYear  %>%
ggplot(aes(x = year,
           y = Emissions,
           color = type)) +
  geom_line() +
   stat_summary(fun = "sum", 
                aes(year, Emissions, color = "Total"), 
                geom="line") +
  scale_color_brewer(palette = "Dark2") +
  ggtitle( label = "Coal Combustion",
           subtitle = "Emissions by Source Type and Year") +
  xlab("Year") + 
  ylab(expression("Total" ~ PM[2.5] ~ "Emissions (Tons)"))
dev.off()
```

### Question 5:

How have emissions from motor vehicle sources changed from 1999–2008 in Baltimore City? --> THEY HAVE DECREASED

```{R}
## Generate data for Baltimore and ON-ROAD

BaltimoreData2 <- subset(NEI,
                         fips == "24510"
                         & type == "ON-ROAD")

#Calculate Sum of emissions by year

BaltimoreMVPM25ByYear <- BaltimoreData2 %>% select(year,
                                                  Emissions) %>%
                                            group_by(year) %>%
                                            summarise_each(funs(sum))
  
#Plot

png("plot5.png")
BaltimoreMVPM25ByYear %>%
ggplot(aes(x = year,
           y = Emissions)) +
  geom_line() +
  ggtitle( label = "Motor Vehicle Emission By Year",
           subtitle = "Baltimore City") +
  xlab("Year") + 
  ylab(expression("Total" ~ PM[2.5] ~ "Emissions (Tons)"))
dev.off()
  
```

### Question 6:
Compare emissions from motor vehicle sources in Baltimore City with emissions from motor vehicle sources in Los Angeles County, California (fips == "06037"). 
Which city has seen greater changes over time in motor vehicle emissions?

```{R}
# Fetch data of type "ON-ROAD" from Baltimore City & Los Angeles County, California
MV <- subset(NEI, (fips == "24510" | fips == "06037") & type=="ON-ROAD")

# Use more meaningful variable names
MV <- transform(MV, region = ifelse(fips == "24510", "Baltimore City", 
                                    "Los Angeles County"))

# Calculate the sum of emission by year and region
MVPM25ByYearAndRegion <- MV %>% select (year, region, Emissions) %>% 
                                group_by(year, region) %>% 
                                summarise_each(funs(sum))

# Create a plot normalized to 1999 levels to better show change over time
Balt1999Emissions <- subset(MVPM25ByYearAndRegion, year == 1999 & 
                              region == "Baltimore City")$Emissions
LAC1999Emissions <- subset(MVPM25ByYearAndRegion, year == 1999 & 
                             region == "Los Angeles County")$Emissions
MVPM25ByYearAndRegionNorm <- transform(MVPM25ByYearAndRegion,
                                       EmissionsNorm = ifelse(region == 
                                                                "Baltimore City",
                                                              Emissions / Balt1999Emissions,
                                                              Emissions / LAC1999Emissions))

#Plot

png("plot6.png")
qplot(year,
      EmissionsNorm,
      data = MVPM25ByYearAndRegionNorm,
      color = region,
      geom = "line") +
  ggtitle(expression("Total" ~ PM[2.5] ~ "Motor Vehicle Emissions Normalized to 1999 Levels")) + 
  xlab("Year") +
  ylab(expression("Normalized" ~ PM[2.5] ~ "Emissions"))
dev.off()
```